# Escuchar en el puerto 1883 para todas las interfaces de red (IPs)
listener 1883 0.0.0.0

# Permitir conexiones sin usuario/password (solo para entorno local/pruebas)
allow_anonymous true

# Configuración de persistencia (opcional pero recomendada)
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
